theme: jekyll-theme-minimal
title: Bonnie</br>The BOM Management Tool
description: A BOM tool for management schematic properties.
logo: https://angeloeyez.github.io/Bonnie-BOM-Management/assets/Logo.png
show_downloads: true
google_analytics: UA-1416817-6
