theme: jekyll-theme-minimal
title: Bonnie The BOM Management Tool
description: A BOM BOM Toolbox
logo: https://angeloeyez.github.io/Bonnie-BOM-Management/assets/Logo.png
show_downloads: true
google_analytics: UA-1416817-6
